### ISSUE TITLE
是否可以读取某个仓库的子目录的代码，因为响应数据过大，基本只能读取一个一个文件，想尝试分某块读取但是显示无法读取和分析子目录内容

### ISSUE THREAD

**Issue by SteveYung-tech** [hlf20010508/gpts-code-analyst#2]
目前，我无法直接读取和分析整个子目录的内容。我只能处理和分析特定的文件。如果您提供了一个文件的完整路径，我可以获取该文件的内容并进行详细分析。

如果您有某个特定子目录下的文件需要分析，您可以提供这些文件的具体路径，例如 `user/repo/path/to/file.ext`。这样我就能够为您提供关于这些特定文件的信息和分析。如果您不确定具体文件名，您可以尝试描述您感兴趣的文件类型或功能，我将尽力协助您。

**Comment by hlf20010508** [comment]
你的意思光目录结构都获取不了？
虽然这个可能性是存在的，可能仓库太大，文件很多，超过github action响应大小的限制了，这样也无解。
这种情况下要只能直接告诉gpt文件的具体路径。
让它阅读xxx/yyy仓库中path/to/file.ext的代码。
![image](https://github.com/hlf20010508/gpts-code-analyst/assets/76218469/550064ec-1faf-4231-8114-4ccce6013f8a)
